/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MatchEventSchema extends BaseModel {
  static $columns = ['createdAt', 'eventType', 'id', 'matchId', 'payloadJson'] as const
  $columns = MatchEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchId: number | null
  @column()
  declare payloadJson: any | null
}

export class MatchSchema extends BaseModel {
  static $columns = ['boardStyle', 'createdAt', 'currentSet', 'fontFamily', 'fouls1', 'fouls2', 'fouls1', 'fouls2', 'id', 'isActive', 'periodTime', 'score1', 'score2', 'screenId', 'setScoresJson', 'shotClockRunning', 'shotClockSeconds', 'sportType', 'status', 'team1Color', 'team1Name', 'team2Color', 'team2Name', 'timeouts1', 'timeouts2', 'updatedAt'] as const
  $columns = MatchSchema.$columns
  @column()
  declare boardStyle: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentSet: number
  @column()
  declare fontFamily: string
  @column()
  declare fouls1: number
  @column()
  declare fouls2: number
  @column()
  declare fouls1: number
  @column()
  declare fouls2: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare periodTime: string | null
  @column()
  declare score1: number
  @column()
  declare score2: number
  @column()
  declare screenId: number | null
  @column()
  declare setScoresJson: any | null
  @column()
  declare shotClockRunning: boolean
  @column()
  declare shotClockSeconds: number
  @column()
  declare sportType: string
  @column()
  declare status: string
  @column()
  declare team1Color: string
  @column()
  declare team1Name: string
  @column()
  declare team2Color: string
  @column()
  declare team2Name: string
  @column()
  declare timeouts1: number
  @column()
  declare timeouts2: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScreenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'ownerUserId', 'slug', 'updatedAt'] as const
  $columns = ScreenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare ownerUserId: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
